# env:
#   es2021: true
#   node: true
#   jest/globals: true
# extends:
#   - eslint:recommended
#   - plugin:@typescript-eslint/recommended
#   - plugin:@typescript-eslint/eslint-recommended
#   # - plugin:@typescript-eslint/recommended-requiring-type-checking
#   - plugin:jest/recommended
#   - prettier
#   - plugin:prettier/recommended
#   - prettier/@typescript-eslint

# parser: '@typescript-eslint/parser'
# parserOptions:
#   ecmaVersion: 12
#   project: './__tests__/tsconfig.json'
#   sourceType: module
# plugins:
#   - '@typescript-eslint'
#   - jest
# rules:
#   jest/expect-expect:
#     - error
#     - assertFunctionNames:
#       - assert
#       - assert*
