version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "write-code-everyday"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dei3ykhenyry"
s3_prefix = "write-code-everyday"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"prd\" ServiceName=\"write-code-everyday\""
