AWSTemplateFormatVersion: '2010-09-09'
Description: create lambda and trigger
Mappings:
  Constants:
    Handler:
      Name: index.handler
    S3:
      BucketName: write-code-everyday-source
      KeyName: lambda.zip
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: System configuration
      Parameters:
      - Env
      - ServiceName
Parameters:
  Env:
    AllowedValues:
    - prd
    - stg
    - dev
    Default: prd
    Type: String
  ServiceName:
    AllowedPattern: ^[a-z0-9-]+$
    Type: String
Resources:
  CrontEventRule:
    Properties:
      Description: event bridge notify everyday
      Name:
        Fn::Sub: ${Env}-${ServiceName}-event-rule
      ScheduleExpression: rate(5 minutes)
      Targets:
      - Arn:
          Fn::GetAtt:
          - Lambda
          - Arn
        Id:
          Fn::Sub: ${Env}-${ServiceName}-lambda
    Type: AWS::Events::Rule
  EventRlePermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: Lambda
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - CrontEventRule
        - Arn
    Type: AWS::Lambda::Permission
  Lambda:
    Properties:
      Code:
        S3Bucket: write-code-everyday-lambda-20210117171117
        S3Key: c65d9bc920a300352c2b3b2f75c841ce
      Description: lambda function treggerd by cloud watch events
      Environment:
        Variables:
          env:
            Ref: Env
      FunctionName:
        Fn::Sub: ${Env}-${ServiceName}-lambda
      Handler:
        Fn::FindInMap:
        - Constants
        - Handler
        - Name
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs12.x
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${Env}-${ServiceName}-lambda
    Type: AWS::Lambda::Function
  LambdaExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: 2012-10-17
      Path: /
      RoleName:
        Fn::Sub: ${Env}-${ServiceName}-lambda-role
    Type: AWS::IAM::Role
